// Generates example/importmap.js from real package resolution.
//
// example/bind.html loads the ESM build, which leaves @observablehq/inputs and
// htl external, so the browser needs an import map for those bare specifiers.
// Hardcoding paths there was brittle: htl 1.0.0 moved src/index.js to
// dist/index.js and silently broke the whole bind suite. Resolving through
// Node's own algorithm means an upstream layout change cannot break the fixture.

import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const exampleDir = new URL("../example/", import.meta.url);

// Bare specifiers the ESM bundle and its dependencies expect at runtime.
const SPECIFIERS = ["@observablehq/inputs", "htl", "isoformat"];

const imports = {};
for (const spec of SPECIFIERS) {
  // import.meta.resolve honours the "exports" map, so it follows the package's
  // declared ESM entry rather than guessing a file layout.
  const resolved = fileURLToPath(import.meta.resolve(spec));
  const rel = relative(fileURLToPath(exampleDir), resolved)
    .split("\\")
    .join("/");
  imports[spec] = rel.startsWith(".") ? rel : `./${rel}`;
}

const out = `// GENERATED by scripts/importmap.mjs — do not edit.
// Run \`npm run build\` to regenerate.
document.currentScript.after(
  Object.assign(document.createElement("script"), {
    type: "importmap",
    textContent: ${JSON.stringify(JSON.stringify({ imports }, null, 2))},
  })
);
`;

writeFileSync(new URL("importmap.js", exampleDir), out);
console.log("importmap ->", JSON.stringify(imports, null, 2));
void here;
